[[main]]
  name = "Docs"
  pageRef = "docs"
  weight = 10

[[main]]
  name = "GitHub"
  url = "https://github.com/moshthesubnet"
  weight = 20

  [main.params]
    icon = "github"
    showName = true
    target = "_blank"
