[[main]]
  name = "Docs"
  pageRef = "docs"
  weight = 10

[[main]]
  name = "GitHub"
  url = "https://github.com/moshthesubnet"
  weight = 20

  [main.params]
    icon = "github"
    showName = true
    target = "_blank"

[[main]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/skylerkingnetwork"
  weight = 30

  [main.params]
    icon = "linkedin"
    showName = true
    target = "_blank"

[[main]]
  name = "Instagram"
  url = "https://instagram.com/moshthesubnet"
  weight = 40

  [main.params]
    icon = "instagram"
    showName = true
    target = "_blank"
