colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
mainSections = ["docs"]

[homepage]
  layout = "page"

[article]
  showDate = false
  showDateUpdated = true
  showReadingTime = false
  showTableOfContents = true

[list]
  showSummary = true
  groupByYear = false

[footer]
  showCopyright = true
  showThemeAttribution = false
