colorScheme = "cyberviolet"
defaultAppearance = "dark"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = true
mainSections = ["docs"]

[header]
  layout = "basic"
  logo = "img/logo.png"
  showTitle = false

[homepage]
  layout = "page"

[article]
  showDate = false
  showDateUpdated = true
  showReadingTime = false
  showTableOfContents = true

[list]
  showSummary = false
  groupByYear = false

[footer]
  showCopyright = true
  showThemeAttribution = false
