baseURL = "https://moshthesubnet.com"
title = "Mosh The Subnet"
theme = "hextra"

enableRobotsTXT = true
enableGitInfo = false  # enable after first git commit
enableInlineShortcodes = true

[outputs]
  home = ["html", "rss"]
  page = ["html"]
  section = ["html", "rss"]

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "docs"
    name = "Docs"
    pageRef = "/docs"
    weight = 1
  [[menu.main]]
    name = "Search"
    weight = 2
    [menu.main.params]
      type = "search"
  [[menu.main]]
    name = "GitHub"
    weight = 3
    url = "https://github.com/moshthesubnet/hugo_website"
    [menu.main.params]
      icon = "github"

[params]
  description = "My documentation site"

  [params.navbar]
    displayTitle = true
    displayLogo = false
    width = "wide"

  [params.theme]
    default = "system"
    displayToggle = true

  [params.footer]
    enable = true
    displayCopyright = true
    displayPoweredBy = false
    width = "normal"

  displayUpdatedDate = true
  dateFormat = "January 2, 2006"

  [params.search]
    enable = true
    type = "flexsearch"
    [params.search.flexsearch]
      index = "content"
      tokenize = "forward"

  [params.highlight]
    [params.highlight.copy]
      enable = true
      display = "hover"

  [params.page]
    width = "normal"
